---
event_type: IssueCommentEvent
avatar: "https://avatars.githubusercontent.com/u/660149?"
user: trws
date: 2025-07-26
repo_name: flux-framework/flux-sched
html_url: https://github.com/flux-framework/flux-sched/issues/1384
repo_url: https://github.com/flux-framework/flux-sched
---

<a href='https://github.com/trws' target='_blank'>trws</a> commented on issue <a href='https://github.com/flux-framework/flux-sched/issues/1384' target='_blank'>flux-framework/flux-sched#1384</a>.

<small>They are not meant to be, but some of them operate on timeouts and can have failures like that especially if the resource is overloaded.  The first of those tests is on a ten second timeout, so I wouldn't expect a spurious failure there unless either launching the subinstance is very delayed (say a very, very slow filesystem) or running too many tests in parallel. ...</small>

<a href='https://github.com/flux-framework/flux-sched/issues/1384' target='_blank'>View Comment</a>